// <auto-generated />
using System;
using Biblioteca.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923193448_EliminarAsistenciaMoverATurno")]
    partial class EliminarAsistenciaMoverATurno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Entities.Informe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("informe");
                });

            modelBuilder.Entity("Biblioteca.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direccion");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NroAfiliado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nro_afiliado");

                    b.Property<string>("ObraSocial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("obra_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("Biblioteca.Entities.PacienteProfesional", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vinculacion");

                    b.HasKey("PacienteId", "ProfesionalId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("paciente_profesional");
                });

            modelBuilder.Entity("Biblioteca.Entities.Profesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Prestacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prestacion");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("RegistroPrestadores")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("registro_prestadores");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("profesional");
                });

            modelBuilder.Entity("Biblioteca.Entities.Reunion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modalidad");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("reunion");
                });

            modelBuilder.Entity("Biblioteca.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_min");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<bool>("Facturable")
                        .HasColumnType("boolean")
                        .HasColumnName("facturable");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<bool>("Justificada")
                        .HasColumnType("boolean")
                        .HasColumnName("justificada");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.Property<int?>("TurnoFijoId")
                        .HasColumnType("integer")
                        .HasColumnName("turno_fijo_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfesionalId");

                    b.HasIndex("TurnoFijoId");

                    b.ToTable("turno");
                });

            modelBuilder.Entity("Biblioteca.Entities.TurnoFijo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<int>("DuracionMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_min");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("interval")
                        .HasColumnName("hora");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("integer")
                        .HasColumnName("profesional_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfesionalId");

                    b.ToTable("turno_fijo");
                });

            modelBuilder.Entity("Biblioteca.Entities.Informe", b =>
                {
                    b.HasOne("Biblioteca.Entities.Paciente", "Paciente")
                        .WithMany("Informes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Biblioteca.Entities.Profesional", "Profesional")
                        .WithMany("Informes")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Biblioteca.Entities.PacienteProfesional", b =>
                {
                    b.HasOne("Biblioteca.Entities.Paciente", "Paciente")
                        .WithMany("PacienteProfesionales")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca.Entities.Profesional", "Profesional")
                        .WithMany("PacienteProfesionales")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Biblioteca.Entities.Reunion", b =>
                {
                    b.HasOne("Biblioteca.Entities.Profesional", "Profesional")
                        .WithMany("Reuniones")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Biblioteca.Entities.Turno", b =>
                {
                    b.HasOne("Biblioteca.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca.Entities.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca.Entities.TurnoFijo", "TurnoFijo")
                        .WithMany("Turnos")
                        .HasForeignKey("TurnoFijoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");

                    b.Navigation("TurnoFijo");
                });

            modelBuilder.Entity("Biblioteca.Entities.TurnoFijo", b =>
                {
                    b.HasOne("Biblioteca.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca.Entities.Profesional", "Profesional")
                        .WithMany()
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Biblioteca.Entities.Paciente", b =>
                {
                    b.Navigation("Informes");

                    b.Navigation("PacienteProfesionales");
                });

            modelBuilder.Entity("Biblioteca.Entities.Profesional", b =>
                {
                    b.Navigation("Informes");

                    b.Navigation("PacienteProfesionales");

                    b.Navigation("Reuniones");
                });

            modelBuilder.Entity("Biblioteca.Entities.TurnoFijo", b =>
                {
                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
